"""Static demo content: Pakistani candidates, companies and jobs. Used by scripts.seed_demo."""

PASSWORD = "demo1234"
CANDIDATE_DOMAIN = "candidates.demo"

# name, gender, age, city, headline, skills, summary,
# education (degree, institute, start year, end year),
# experience [(title, employer, start MM/YYYY, end MM/YYYY or Present, what they did)]
CANDIDATES = [
    dict(name="Ahmed Raza", gender="male", age=27, city="Lahore", headline="Backend Engineer",
         skills=["Python", "FastAPI", "Django", "PostgreSQL", "Docker", "Redis"],
         summary="Backend engineer with 5 years of experience building scalable REST APIs and payment services for Pakistani fintech products.",
         edu=("BS Computer Science", "FAST-NUCES Lahore", 2015, 2019),
         exp=[("Backend Engineer", "Sapphire Systems", "03/2021", "Present", "Designed FastAPI microservices handling 2M requests a day."),
              ("Software Engineer", "CodeBridge Pvt Ltd", "07/2019", "02/2021", "Built Django admin tools and PostgreSQL reporting.")]),
    dict(name="Fatima Zahra", gender="female", age=25, city="Karachi", headline="Frontend Developer",
         skills=["React", "TypeScript", "Next.js", "Tailwind", "Figma", "JavaScript"],
         summary="Frontend developer who turns Figma designs into fast, accessible React interfaces for e-commerce and SaaS teams.",
         edu=("BS Software Engineering", "NED University of Engineering & Technology", 2017, 2021),
         exp=[("Frontend Developer", "Pixel Forge Studios", "09/2022", "Present", "Led the React and TypeScript rebuild of a retail web app."),
              ("Junior Web Developer", "Karachi Web Works", "08/2021", "08/2022", "Delivered responsive landing pages with Tailwind.")]),
    dict(name="Ali Hassan", gender="male", age=29, city="Islamabad", headline="Data Analyst",
         skills=["SQL", "Power BI", "Python", "Pandas", "Excel", "Tableau"],
         summary="Data analyst turning raw operational data into dashboards that managers actually use. Experienced in telecom and retail analytics.",
         edu=("BS Computer Science", "COMSATS University Islamabad", 2013, 2017),
         exp=[("Data Analyst", "DataHive Analytics", "01/2020", "Present", "Built Power BI dashboards and automated weekly SQL reports."),
              ("Business Analyst", "Margalla Retail Group", "06/2017", "12/2019", "Analysed sales trends across 40 stores in Python and Excel.")]),
    dict(name="Ayesha Siddiqui", gender="female", age=26, city="Karachi", headline="Machine Learning Engineer",
         skills=["Python", "Machine Learning", "TensorFlow", "Scikit-learn", "NLP", "SQL"],
         summary="Machine learning engineer focused on NLP for Urdu and English text, from experimentation to production deployment.",
         edu=("BS Computer Science", "Habib University", 2016, 2020),
         exp=[("Machine Learning Engineer", "Neuron Labs", "02/2021", "Present", "Trained text classification models and served them with FastAPI."),
              ("Data Science Intern", "DataHive Analytics", "06/2020", "12/2020", "Prototyped churn prediction models in Scikit-learn.")]),
    dict(name="Hamza Malik", gender="male", age=30, city="Rawalpindi", headline="DevOps Engineer",
         skills=["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Linux"],
         summary="DevOps engineer who automates infrastructure and delivery pipelines. Cut deployment time from hours to minutes for three product teams.",
         edu=("BS Software Engineering", "NUST (SEECS)", 2012, 2016),
         exp=[("DevOps Engineer", "CloudNine Pakistan", "05/2019", "Present", "Managed EKS clusters and Terraform modules on AWS."),
              ("Systems Administrator", "Rawal Networks", "08/2016", "04/2019", "Maintained Linux servers and monitoring.")]),
    dict(name="Zainab Tariq", gender="female", age=24, city="Lahore", headline="UI/UX Designer",
         skills=["Figma", "UI/UX", "Prototyping", "User Research", "Adobe XD", "Design Systems"],
         summary="Product designer who runs user research and builds design systems for mobile and web products.",
         edu=("BFA Visual Communication Design", "National College of Arts (NCA) Lahore", 2017, 2021),
         exp=[("UI/UX Designer", "Pixel Forge Studios", "10/2021", "Present", "Redesigned onboarding, lifting activation by 18 percent."),
              ("Design Intern", "Lahore Creative Hub", "05/2021", "09/2021", "Created wireframes and brand assets.")]),
    dict(name="Usman Ghani", gender="male", age=28, city="Faisalabad", headline="Mobile App Developer",
         skills=["Flutter", "Dart", "Firebase", "Android", "REST APIs", "Git"],
         summary="Mobile developer shipping Flutter apps to the Play Store and App Store, including a delivery app with 100k downloads.",
         edu=("BS Computer Science", "FAST-NUCES Chiniot-Faisalabad", 2014, 2018),
         exp=[("Flutter Developer", "AppNest Technologies", "04/2020", "Present", "Built and maintained 4 production Flutter apps."),
              ("Android Developer", "Textile City Software", "07/2018", "03/2020", "Developed Android apps in Kotlin and Java.")]),
    dict(name="Sana Iqbal", gender="female", age=27, city="Islamabad", headline="QA Automation Engineer",
         skills=["Selenium", "Cypress", "Postman", "API Testing", "Jira", "Python"],
         summary="QA automation engineer who builds reliable end-to-end and API test suites and reduces regression time.",
         edu=("BS Software Engineering", "Bahria University Islamabad", 2014, 2018),
         exp=[("QA Automation Engineer", "Margalla Technologies", "02/2020", "Present", "Automated 600 regression tests in Cypress."),
              ("QA Engineer", "TestWorks Pakistan", "09/2018", "01/2020", "Manual and API testing with Postman.")]),
    dict(name="Bilal Ahmed", gender="male", age=31, city="Karachi", headline="Full Stack Developer",
         skills=["Node.js", "React", "MongoDB", "Express", "GraphQL", "TypeScript"],
         summary="Full stack developer with 8 years of experience shipping MERN products for startups across Karachi and the Gulf.",
         edu=("BS Computer Science", "IBA Karachi", 2011, 2015),
         exp=[("Senior Full Stack Developer", "Gulf Digital Partners", "01/2019", "Present", "Led a team of 4 building a GraphQL and React platform."),
              ("Software Developer", "Indus Digital", "07/2015", "12/2018", "Built Node.js APIs and React dashboards.")]),
    dict(name="Hira Khan", gender="female", age=28, city="Peshawar", headline="Business Intelligence Analyst",
         skills=["SQL", "Tableau", "Power BI", "Python", "Statistics", "Excel"],
         summary="BI analyst with a statistics background, delivering KPI dashboards and forecasting for healthcare and NGO clients.",
         edu=("BS Statistics", "University of Peshawar", 2013, 2017),
         exp=[("BI Analyst", "Khyber Health Analytics", "03/2019", "Present", "Created Tableau dashboards used by 200 clinics."),
              ("Research Assistant", "University of Peshawar", "09/2017", "02/2019", "Statistical modelling in Python.")]),
    dict(name="Muhammad Umer Farooq", gender="male", age=26, city="Multan", headline="Java Backend Developer",
         skills=["Java", "Spring Boot", "MySQL", "Microservices", "Kafka", "Docker"],
         summary="Java backend developer building event-driven Spring Boot microservices for banking clients.",
         edu=("BS Computer Science", "Bahauddin Zakariya University Multan", 2015, 2019),
         exp=[("Java Developer", "Punjab Software House", "08/2019", "Present", "Developed Spring Boot services and Kafka consumers."),
              ("Intern", "Multan IT Solutions", "03/2019", "07/2019", "Worked on MySQL schema design.")]),
    dict(name="Maryam Shah", gender="female", age=29, city="Lahore", headline="Product Manager",
         skills=["Product Management", "Agile", "Jira", "Analytics", "Roadmapping", "Stakeholder Management"],
         summary="Product manager who has launched three B2B products, owning roadmap, discovery and delivery with engineering teams.",
         edu=("MBA", "LUMS (Suleman Dawood School of Business)", 2018, 2020),
         exp=[("Product Manager", "Punjab Software House", "07/2020", "Present", "Owned the roadmap for a logistics SaaS used in 5 cities."),
              ("Business Analyst", "Lahore Consulting Group", "06/2017", "06/2018", "Gathered requirements and wrote user stories.")]),
    dict(name="Saad Qureshi", gender="male", age=25, city="Karachi", headline="Full Stack Engineer",
         skills=["React", "Node.js", "Python", "FastAPI", "MySQL", "Docker"],
         summary="Full stack engineer comfortable across React frontends and Python APIs, with a focus on clean data models.",
         edu=("BS Software Engineering", "Sir Syed University of Engineering & Technology", 2017, 2021),
         exp=[("Full Stack Engineer", "Indus Digital", "09/2021", "Present", "Built internal HR tools with React and FastAPI."),
              ("Trainee Engineer", "Karachi Soft", "01/2021", "08/2021", "Worked on MySQL reports.")]),
    dict(name="Noor Fatima", gender="female", age=23, city="Lahore", headline="Digital Marketing Executive",
         skills=["Digital Marketing", "SEO", "Google Analytics", "Content Strategy", "Social Media", "Copywriting"],
         summary="Digital marketer growing organic traffic through SEO and content, with hands-on experience running Meta and Google campaigns.",
         edu=("BBA Marketing", "University of the Punjab", 2018, 2022),
         exp=[("Digital Marketing Executive", "Zameen Media House", "06/2022", "Present", "Grew organic traffic 70 percent in 9 months."),
              ("Marketing Intern", "Lahore Creative Hub", "01/2022", "05/2022", "Managed social media calendars.")]),
    dict(name="Hassan Mehmood", gender="male", age=33, city="Islamabad", headline=".NET Developer",
         skills=["C#", ".NET", "Azure", "SQL Server", "Microservices", "Entity Framework"],
         summary="Senior .NET developer with 10 years of experience in enterprise and government systems, now focused on Azure microservices.",
         edu=("BS Computer Science", "Air University Islamabad", 2009, 2013),
         exp=[("Senior .NET Developer", "Capital Systems Ltd", "02/2017", "Present", "Moved a monolith to Azure microservices."),
              ("Software Engineer", "Federal IT Solutions", "09/2013", "01/2017", "Built ASP.NET MVC applications.")]),
    dict(name="Areeba Anwar", gender="female", age=24, city="Karachi", headline="Software Engineer",
         skills=["Python", "Django", "REST", "PostgreSQL", "React", "Git"],
         summary="Software engineer who enjoys building Django back ends and the React front ends that sit on top of them.",
         edu=("BS Computer Science", "Dawood University of Engineering & Technology", 2017, 2021),
         exp=[("Software Engineer", "Sapphire Systems", "10/2021", "Present", "Shipped Django REST features and React admin screens."),
              ("Intern", "Karachi Soft", "06/2021", "09/2021", "Wrote unit tests and small Django features.")]),
]

# Demo companies: key, name, email, city, employees, about, linkedin
COMPANIES = [
    dict(key="indus", name="Indus Digital", email="hr@indusdigital.demo", city="Karachi, Pakistan", employees=180,
         about="Karachi-based digital product company building fintech, logistics and e-commerce platforms for clients across Pakistan and the Gulf.",
         linkedin="https://linkedin.com/company/indus-digital-demo"),
    dict(key="margalla", name="Margalla Technologies", email="hr@margalla.demo", city="Islamabad, Pakistan", employees=90,
         about="Islamabad technology firm specialising in AI, cloud and data engineering for government and enterprise customers.",
         linkedin="https://linkedin.com/company/margalla-technologies-demo"),
    dict(key="punjab", name="Punjab Software House", email="hr@punjabsoftware.demo", city="Lahore, Pakistan", employees=250,
         about="One of Lahore's established software houses: web, mobile and design services for startups and enterprises worldwide.",
         linkedin="https://linkedin.com/company/punjab-software-house-demo"),
]

# company key, role, type, min salary, max salary (PKR per month), required skills, intro sentence, also_for_existing_company
JOBS = [
    ("indus", "Senior Backend Engineer", "full time", "350,000", "550,000", ["Python", "FastAPI", "PostgreSQL", "Docker", "Redis"],
     "Own and scale the APIs behind our payments platform in Karachi.", True),
    ("indus", "Flutter Developer", "hybrid", "200,000", "320,000", ["Flutter", "Dart", "Firebase", "REST APIs", "Android"],
     "Build our customer-facing mobile apps used across Pakistan.", False),
    ("indus", "Data Analyst", "onsite", "150,000", "250,000", ["SQL", "Power BI", "Python", "Excel", "Tableau"],
     "Turn operational data into dashboards for our logistics teams.", True),
    ("indus", "QA Automation Engineer", "full time", "180,000", "280,000", ["Selenium", "Cypress", "Postman", "API Testing", "Jira"],
     "Build automated test suites that keep every release safe.", False),
    ("margalla", "Machine Learning Engineer", "remote", "400,000", "650,000", ["Python", "TensorFlow", "Scikit-learn", "NLP", "Machine Learning"],
     "Develop and deploy NLP models for government and enterprise clients.", True),
    ("margalla", "DevOps Engineer", "hybrid", "350,000", "500,000", ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
     "Run our cloud platform and deployment pipelines from Islamabad.", True),
    ("margalla", "Java Spring Boot Developer", "full time", "300,000", "450,000", ["Java", "Spring Boot", "MySQL", "Microservices", "Kafka"],
     "Build event-driven services for banking customers.", False),
    ("margalla", "Product Manager", "full time", "400,000", "600,000", ["Product Management", "Agile", "Jira", "Analytics", "Roadmapping"],
     "Define the roadmap for our data platform products.", False),
    ("punjab", "React Frontend Developer", "hybrid", "220,000", "380,000", ["React", "TypeScript", "Tailwind", "Next.js", "Figma"],
     "Create fast, polished web interfaces for international clients.", True),
    ("punjab", "Full Stack Engineer", "full time", "300,000", "480,000", ["React", "Node.js", "Python", "MySQL", "Docker"],
     "Work across our React frontends and Python and Node services.", False),
    ("punjab", "UI/UX Designer", "contract", "150,000", "260,000", ["Figma", "UI/UX", "Prototyping", "User Research", "Design Systems"],
     "Design the next generation of our mobile and web products.", False),
    ("punjab", "Digital Marketing Executive", "full time", "100,000", "180,000", ["Digital Marketing", "SEO", "Google Analytics", "Content Strategy", "Social Media"],
     "Grow our brand and generate leads through content and campaigns.", False),
    ("punjab", ".NET Developer", "contract", "280,000", "420,000", ["C#", ".NET", "Azure", "SQL Server", "Microservices"],
     "Modernise enterprise applications on Azure.", False),
]

NOTES = [
    "Strong technical screen. Clear communicator.",
    "Good portfolio. Check notice period.",
    "Salary expectation slightly above range, still worth proceeding.",
    "Impressive project ownership. Schedule with the team lead.",
    "Reference check pending.",
]

# Roles open to one gender only (common in Pakistan); everything else is open to all
GENDER_ONLY = {
    "UI/UX Designer": "female",
    "Digital Marketing Executive": "female",
    "Flutter Developer": "male",
}
